name: spotflow
description: "Spotflow Flutter project."
version: 0.0.1-beta.1
homepage: https://spotflow.co

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  credit_card_validator: ^2.1.0
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_multi_formatter: ^2.12.8
  flutter_svg: ^2.0.10+1
  pin_code_fields: ^8.0.1
  simple_ripple_animation: ^0.0.9
  uuid: ^4.4.2
  encrypt: ^5.0.3
  pattern_formatter: ^4.0.0
  provider: ^6.1.2
  vector_graphics: ^1.1.11+1
  webview_flutter: ^4.8.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.5.0+1


flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true
    # Optional
  integrations:
    flutter_svg: true



flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/json/

